mib/models/message.py
class Message():
    """Representation of Message model."""

    def __init__(self,
                 id=None,
                 sender_id=None,
                 recipient_id=None,
                 text=None,
                 delivery_date=None,
                 is_draft=None,
                 is_delivered=None,
                 is_read=None
        ):
        #Data
        self.id = id
        self.sender_id = sender_id
        self.recipient_id = recipient_id
        self.text = text
        self.delivery_date = delivery_date
        self.sender = {'first_name': None, 'last_name': None}
        self.recipient = {'first_name': None, 'last_name': None}
        # Booleans
        self.is_draft = is_draft
        self.is_delivered = is_delivered
        self.is_read = is_read
 

mib/forms/login.py
import wtforms as f

from flask_wtf import FlaskForm
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Form created to allow users to login."""

    email = f.StringField(
        'Email',
        validators=[DataRequired()],
        id="inputEmail",
    )
    password = f.PasswordField('Password', validators=[DataRequired()])

    display = ['email', 'password']

mib/forms/message.py
from datetime import datetime

from flask_wtf import FlaskForm
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateTimeLocalField
from wtforms import SubmitField, SelectMultipleField, IntegerField,TextAreaField
from wtforms.widgets import HiddenInput


class MessageForm(FlaskForm):
    """Message form during writing of message."""

    message_id_hidden = IntegerField(widget=HiddenInput(), default=-1)
    text_area = TextAreaField('Write your message here!', id='text')
    delivery_date = DateTimeLocalField(
                                    'Delivery Date',
                                    validators=[
                                        DataRequired()], format='%Y-%m-%dT%H:%M')
    users_list = SelectMultipleField('Select recipients', id='users_list')
    save_button = SubmitField('Save')
    send_button = SubmitField('Send')

    display = ['text_area', 'delivery_date', 'users_list']

    def validate_on_submit(self):
        """Input check: the delivery date chosen isn't before current time."""
        
        if self.delivery_date.data is None or self.delivery_date.data < datetime.now():
            return False
        if (self.send_button.data) and (self.users_list.data == []):
            return False

        return True

mib/forms/user.py
import wtforms as f

from flask_wtf import FlaskForm
from wtforms.fields.html5 import DateField, EmailField
from wtforms.validators import DataRequired, Email
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired

from mib.validators.validators import EmailValidator, PasswordValidator, AgeValidator


class UserForm(FlaskForm):
    """Form created to allow the customers sign up to the application.
    This form requires all the personal information, in order to create the account.
    """

    email = EmailField(
        'Email',
        validators=[DataRequired(), EmailValidator(), Email(check_deliverability=True)]
    )

    firstname = f.StringField(
        'Firstname',
        validators=[DataRequired()]
    )

    lastname = f.StringField(
        'Lastname',
        validators=[DataRequired()]
    )

    password = f.PasswordField(
        'Password',
        validators=[DataRequired(), PasswordValidator()]
    )

    date_of_birth = DateField(
        'Birthday',
        validators=[AgeValidator(min_age=18)]
    )

    location = f.StringField(
        'Location', 
        validators=[DataRequired()]
    )

    display = ['email', 'firstname', 'lastname', 'password',
               'date_of_birth', 'location']


class UserProfileForm(FlaskForm):
    """Form created to allow the customers sign up to the application.
    This form requires all the personal information, in order to create the account.
    """

    email = EmailField(
        'Email',
        render_kw={"readonly": True},
        validators=[DataRequired(), Email(check_deliverability=True)]
    )

    firstname = f.StringField(
        'Firstname',
        render_kw={"readonly": True},
        validators=[DataRequired()]
    )

    lastname = f.StringField(
        'Lastname',
        render_kw={"readonly": True},
        validators=[DataRequired()]
    )


    location = f.StringField(
        'Location',
        render_kw={"readonly": True},
        validators=[DataRequired()]
    )
    
    bonus = f.StringField(
        'Bonus',
        render_kw={"readonly": True},
        validators=[DataRequired()]
    )

    profile_pic = FileField(
                    validators=[FileRequired(), FileAllowed(['png', 'jpg', 'jpg'], 'Images only!')])

    display = ['firstname', 'lastname', 'email',
               'location', 'bonus', 'profile_pic']


class UnregisterForm(FlaskForm):
    """Form created to allowed the users unregistration from the application.
    This form requires the user password in order unregistrate the account.
    """

    password = f.PasswordField(
        'Password',
        validators=[DataRequired()]
    )

    display = ['password']

mib/views/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)


@home.route('/', methods=['GET', 'POST'])
def index():
    """General route for the index page."""
    return render_template("index.html")

mib/views/messages.py
import bleach
import json
from flask import Blueprint, redirect, render_template, request
from flask_login import current_user

from .auth import login_required
#from ..background import notify
from .utils import get_argument

from mib.forms.message import MessageForm
from mib.rao.user_manager import UserManager
from mib.rao.message_manager import MessageManager
from mib.rao.blacklist_manager import BlacklistManager


messages = Blueprint('messages', __name__)


allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                'h1', 'h2', 'h3', 'img', 'video','p', 'div', 'iframe',
                'br', 'span', 'hr', 'src', 'class','font','u']

allowed_attrs = {'*': ['class','style','color'],
                 'a': ['href', 'rel'],
                 'img': ['src', 'alt','data-filename','style']}


@messages.route('/message/<int:message_id>', methods=['GET', 'DELETE'])
@login_required
def message(message_id):
    '''Allows the user to read or delete a specific message by id.

       GET: display the content of a specific message by id (censored if language_filter is ON)
       DELETE:
    '''
    bonus = UserManager.get_bonus(current_user.get_id())

    try: 
        _message = MessageManager.get_message_by_id(current_user.get_id(), message_id)
    except RuntimeError as e:
        message='ERROR contacting message microservice'
        return render_template('error.html', error=message)

    if request.method == 'GET':
        # Get sender and recipient first and last names.
        try:
            sender = UserManager.get_profile_by_id(_message.sender_id)
            recipient = UserManager.get_profile_by_id(_message.recipient_id)
            _message.sender['first_name'], _message.sender['last_name'] = sender.first_name, sender.last_name
            _message.recipient['first_name'], _message.recipient['last_name'] = recipient.first_name, recipient.last_name
        except:
            fake_name = 'Undefined'
            _message.sender['first_name'] = _message.sender['last_name'] = fake_name
            _message.recipient['first_name'] = _message.recipient['last_name'] = fake_name

        return render_template('message.html', bonus=bonus, message=_message)
    
    # DELETE
    try:
        MessageManager.delete_message_by_id(current_user.get_id(), message_id)
        if not _message.is_draft and not _message.is_delivered and bonus > 0:
            bonus -= 1
            UserManager.set_bonus(current_user.get_id(), bonus)
    except:
        message = 'Error in deleting the message'
        return render_template('error.html', error=message)

    return redirect("/mailbox")


@messages.route('/mailbox')
def mailbox():
    '''Manage the user's sent and received messages, aswell as the drafts.
       GET: display the list of drafts, sent and received messages
       POST: perform an action on drafts and messages
             if <message> in <sent_messages> AND <To> button is clicked: display information about the recipient
             if <message> in <received_messages> AND <From> button is clicked: display information about the sender
             if <message> in <draft_messages>
             if <Edit> button is clicked: allows to edit the message text, delivery_date and recipients
             if <View> button is clicked: display the message information
    '''
    id = current_user.get_id()

    # Retrieve all messages of user <id>
    try:
        sent_messages, received_messages, draft_messages, _ = MessageManager.get_all_messages(id)
    except:
        sent_messages = received_messages = draft_messages = []

    try:
        for message in sent_messages:
            recipient = UserManager.get_profile_by_id(message.recipient_id)
            message.recipient['first_name'], message.recipient['last_name'] = recipient.first_name, recipient.last_name
        for message in received_messages:
            sender = UserManager.get_profile_by_id(message.sender_id)
            message.sender['first_name'], message.sender['last_name'] = sender.first_name, sender.last_name
    except:
        fake_name = 'Undefined'
        for message in sent_messages: message.recipient['first_name'] = message.recipient['last_name'] = fake_name
        for message in received_messages: message.sender['first_name'] = message.sender['last_name'] = fake_name

    return render_template('mailbox.html', sent_messages=sent_messages,
                                           received_messages=received_messages,
                                           draft_messages=draft_messages
    )


@messages.route('/create_message', methods=['GET', 'POST'])
@login_required
def create_message():
    '''Manage the creation, reply, and the forward of messages and drafts.
       GET: Creates the form for editing/writing a message.
            If <draft_id> is specified, the corresponding draft is loaded.
            If <forw_id> is specified, the corresponding message is loaded.
            If <reply_id> is specified, the corresponding recipient is loaded.
       POST: Takes the input from the form, creates a new Message object and save it on DB:
             As draft if the <save button> is clicked, as message to send otherwise.
    '''
    form = MessageForm()
    user_id = current_user.get_id()

    if request.method == 'POST':
        error = None

        # Save the choices of recipients.
        form.users_list.choices = form.users_list.data
        if form.validate_on_submit():
            clean_text = bleach.clean(form.text_area.data, tags=allowed_tags, strip=True,
                attributes=allowed_attrs, protocols=['data'], styles='background-color'
            )

            # Save draft.
            if form.save_button.data:
                draft_message = {
                    'text': clean_text,
                    'delivery_date': str(form.delivery_date.data),
                    'sender_id': user_id,
                    'is_draft': True,
                    'recipient_id': 0
                }
                body = json.dumps({'message': draft_message})

                try:
                    # Update old draft.
                    if form.message_id_hidden.data > 0:
                        MessageManager.update_message(user_id, form.message_id_hidden.data, body)

                    # Create new draft.
                    else:
                        MessageManager.create_message(body)
                except:
                    return redirect('/mailbox')

            # Send.
            else:
                blocked_users = BlacklistManager.get_blocked_users(user_id).json()['blocked_users']
                for recipient in form.users_list.data:
                    if recipient in blocked_users:
                        continue

                    message = {
                        'text': clean_text,
                        'delivery_date': str(form.delivery_date.data),
                        'sender_id': user_id,
                        'is_draft': False,
                        'recipient_id': recipient
                    }
                    body = json.dumps({'message': message})

                    try:
                        # Sending a draft.
                        if form.message_id_hidden.data > 0:
                            MessageManager.update_message(user_id, form.message_id_hidden.data, body)
                            form.message_id_hidden.data = -1

                        # Sending a new message.
                        else:
                            MessageManager.create_message(body)
                    except:
                        return redirect('/mailbox')
         
            return redirect('/mailbox')

        else:
            error = '''
                <h3>Wrong data provided!</h3><br/>
                Rules:<br/>  
                    1. Delivery date must be in the future!<br/>
                    2. Recipient field can\'t be empty!
                '''
            # Conflict
            return render_template('/error.html', error=error), 409
    
    # GET
    else:
        form.users_list.choices = [
            (user.get_id(), user.get_email()) for user in UserManager.get_users_list()
        ]
        selected = 0

        draft_id = get_argument(request, 'draft_id', int)
        forw_id = get_argument(request, 'forw_id', int)
        reply_id = get_argument(request, 'reply_id', int)

        if draft_id is not None:
            try:
                message = MessageManager.get_message_by_id(user_id, draft_id)
            except:
                error = '<h3>Error!</h3><br/> The message is not correct!'
                return render_template('/error.html', error=error), 403

            if not message.is_draft:
                error = '<h3>Error!</h3><br/> The message is not a draft!'
                return render_template('/error.html', error=error), 403

            form.message_id_hidden.data = message.id
            form.text_area.data = message.text
            form.delivery_date.data = message.delivery_date

        elif forw_id is not None:
            try:
                message = MessageManager.get_message_by_id(user_id, forw_id)
            except:
                error = '<h3>Error!</h3><br/> The message is not correct!'
                return render_template('/error.html', error=error), 403

            # draft or scheduled message
            if message.is_draft or not message.is_delivered:
                error = '<h3>Error!</h3><br/> you can\'t forward this message!'
                return render_template('/error.html', error=error), 403

            form.text_area.data = f'Forwarded: {message.text}'

        elif reply_id is not None:
            try:
                message = MessageManager.get_message_by_id(user_id,reply_id)
            except:
                error = '<h3>Error!</h3><br/> The message is not correct!'

mib/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- include libraries(jQuery, Popper, Bootstrap) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/utils.js') }}"></script>

    <title>Message in a Bottle - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style3.css') }}">
    {% block head %}
    {% endblock %}
</head>

<body>

{% block navbar %}
    {% if current_user.is_authenticated %}
        {% if current_user.is_admin %}
            {% include "components/navbar/admin_navbar.html" %}
        {% else %}
            {% include "components/navbar/user_navbar.html" %}
        {% endif %}
    {% else %}
        {% include "components/navbar/anonymous_navbar.html" %}
    {% endif %}
{% endblock %}

<main role="main" class="container">
    {% block flashing_messages %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="row">
                    <div class="col-md-12">
                        <ul class="flashes">
                            {% for message in messages %}
                                <div class="alert alert-warning">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
        {% endwith %}
    {% endblock %}

    {% block content %}
    {% endblock %}
</main>

{% block scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

{% endblock scripts %}
{% block footer %}
    <footer class="footer">
        <div class="container">
            <span class="text-muted">Message in a Bottle &copy;</span>
        </div>
    </footer>
{% endblock %}
</body>
</html>

mib/templates/calendar.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/calendar.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">

<h1>Calendar</h1>
  <div id="calendar"></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
  <script>
    document.addEventListener("DOMContentLoaded", async () => {
    const cal = Calendar('calendar');
    cal.bindData({{ data|safe }});
    cal.render();
  });
  </script>

{% endblock %}

mib/templates/create_message.html
{% extends "base.html" %}
{% block content %}

<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

<!-- include selectize css/js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.css" rel="stylesheet">


<form action="" method="POST" enctype="multipart/form-data" onsubmit="return validateForm()">
  {{ form.hidden_tag() }}
  <dl>
  {% for field in form.display %}
  <dt>{{ form[field].label }}</dt>
  <dd>{{ form[field]() }}</dd>
    {% if form[field].errors %}
        {% for e in form[field].errors %}
        <p class="help-block">{{ e }}</p>
        {% endfor %}
    {% endif %}
  {% endfor %}

  {% if error %}
  <p><strong> Error: </strong></p> {{error}}
  {% endif %}

  </dl>
  <p>
  </p>
  <input type=submit name='save_button' value="Save" class="my_button">
  <input type=submit name='send_button' value="Send" class="my_button">
</form>

<script>
  // Fancy multiple recipients with selectize
  const list = $("#users_list").selectize({placeholder: 'Select recipients', create: true})
  const selectize = list[0].selectize
  selectize.setValue({{selected}})
  
  // Fancy textfield with summernote
  $("#text").summernote();
</script>

{% endblock %}

mib/templates/create_user.html
{% extends "base.html" %}
{% from 'bootstrap/wtf.html' import form_field %}

{% block title %} Sign up {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Sign up</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {{ form.hidden_tag() }}

                {% for field in form.display %}
                    {{ form_field(form[field]) }}
                {% endfor %}
                <input type=submit value="Signup" class="btn btn-primary">
            </form>
        </div>
    </div>


{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/error.html
{% extends "base.html" %}
{% block content %}

{{ error|safe }}
<br>
<input type="button" onclick="history.back();" value="Back" class="my_button"/>

{% endblock %}

mib/templates/index.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="d-flex justify-content-center">
            <div class="row" position="absolute">
                <img src="/static/img/icon2.png" width="70" height="70" class="d-inline-block align-top" alt="" >
                <h1 class ="display-4" >Message in a Bottle</h1>
            </div>
        </div>
        <div class="d-flex justify-content-center">
        <p class="lead">
            Welcome!
        </p>
        </div>
        <hr class="my-4">
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block flashing_messages %}
{% endblock %}
{% block content %}
    <form class="form-signin" action="" method="POST">
        {{ form.hidden_tag() }}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
               autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="btn btn-lg btn-secondary btn-block" 
                href="{{ url_for('home.index') }}">Go back</a>
        {% if re_login %}
            <br/>
            <div class="alert alert-warning" role="alert">
                Your session is expired, please login again.
            </div>
        {% endif %}
    </form>
{% endblock %}

{% block footer %}
{% endblock %}

mib/templates/mailbox.html
{% extends "base.html" %}
{% block content %}

<div>
  <div id='sent' style='width: 33%; float: left'>
    <h2>Sent messages</h2>
    <ul>
      {% for message in sent_messages: %}
        <li>
          <a href="/message/{{message.id}}">To</a> {{message.recipient.first_name}} {{message.recipient.last_name}} {{message.text|jBleach|safe}}
        </li>
      {% endfor %}
    </ul>
  </div>

  <div id='received' style='width: 34%; float: left'>
    <h2>Received messages</h2>
    <ul>
      {% for message in received_messages: %}
          <li>
            <a href="/message/{{message.id}}">From</a> {{message.sender.first_name}} {{message.sender.last_name}}
          </li>
      {% endfor %}
    </ul>
  </div>

  <div id='drafts' style='width: 32%; float: left'>
    <h2>Draft messages</h2>
    <ul>
      {% for message in draft_messages: %}
          <li>
            {{message.text|jBleach|safe}}
            <a href="/create_message?draft_id={{message.id}}">Edit</a> 
            <a href="/message/{{message.id}}">View</a> 
          </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

mib/templates/message.html
{% extends "base.html" %}
{% block content %}

<h1>Message</h1>
  Text: {{message['text']|safe}} <br> 
  On: {{message['delivery_date']}} <br>
  From: {{message.sender.first_name}} {{message.sender.last_name}} <br>
  To: {{message.recipient.first_name}} {{message.recipient.last_name}}<br><br>
  {% if (not message.is_draft and not message.is_delivered and bonus > 0) or 
         message.is_draft or message.is_delivered %}
    <button type="submit" onclick="DeleteMessage('{{message.id}}')" class="my_button">Delete</button>
  {% endif %}
  {% if not message.is_draft and message.is_delivered %}
    <a href="/create_message?forw_id={{message.id}}"> <button class="my_button">Forward</button> </a>
    <a href="/create_message?reply_id={{message.id}}"> <button class="my_button">Reply</button> </a>
  {% endif %}      
<br> <br>
<a href="/mailbox"> <button class="my_button">Back to Mailbox</button> </a>

{% endblock %}

mib/templates/moderation.html
{% extends "base.html" %} {% block title %} Reported Users {% endblock %} {% block content %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-uppercase mb-0">Reported Users</h5>
                </div>
                <div class="table-responsive">
                    <table class="table no-wrap user-table mb-0">
                        <thead>
                            <tr>
                                <th scope="col" class="border-0 text-uppercase font-medium pl-4">ID</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Name</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Email</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Location</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Moderate</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in reported_users %}
                            <tr>
                                <td class="pl-4">{{ user.id }}</td>
                                <td>
                                    <h6 class="font-medium mb-0"> {{ user.first_name }} {{ user.last_name }}</h6>
                                </td>
                                <td>
                                    <span class="text-muted"> {{ user.email }}</span><br>
                                </td>
                                <td>
                                    <span class="text-muted"> {{ user.location }}</span><br>
                                </td>
                                <td>
                                    <form action="/moderation/" method="POST">
                                        <button type="submit" name="action" value="Reject" class="btn btn-success btn-xs">Reject</button>
                                        <button type="submit" name="action" value="Ban" class="btn btn-danger btn-xs">Ban
                                </button>
                                        <input type="hidden" id="id" name="id" value="{{ user.id }}">
                                    </form>
                                </td>
                            </tr>
                            {% endfor %} {% for user in banned_users %}
                            <tr>
                                <td class="pl-4">{{ user.id }}</td>
                                <td>
                                    <h6 class="font-medium mb-0"> {{ user.first_name }} {{ user.last_name }}</h6>
                                </td>
                                <td>
                                    <span class="text-muted"> {{ user.email }}</span><br>
                                </td>
                                <td>
                                    <span class="text-muted"> {{ user.location }}</span><br>
                                </td>
                                <td>
                                    <form action="/moderation/" method="POST">
                                        <button type="submit" name="action" value="Unban" class="btn btn-success btn-xs">Unban
                                        </button>
                                        <input type="hidden" id="id" name="id" value="{{ user.id }}">
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block footer %} {% endblock %}

mib/templates/schedule.html
{% extends "base.html" %}
{% block content %}

<div>
  <div id='scheduled'>
    <h2>Scheduled messages</h2>
    <ul>
      {% for message in scheduled_messages: %}
        <li>
          <a href="/message/{{message.id}}">To</a> {{message.recipient.first_name}} {{message.recipient.last_name}} {{message.text|jBleach|safe}}
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

mib/templates/unregister.html
{% extends "base.html" %}
{% from 'bootstrap/wtf.html' import form_field %}

{% block title %} Sign up {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="display-4">Unregister</h2>
            <p>Please, insert your password to confirm the unregistration.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {{ form.hidden_tag() }}

                {% for field in form.display %}
                    {{ form_field(form[field]) }}
                {% endfor %}
                <input type=submit value="Unregister" class="btn btn-primary">
            </form>
        </div>
    </div>


{% endblock %}

{% block footer %}
{% endblock %}